name: Update BSB Database

on:
  schedule:
    # https://crontab.guru/every-month
    # At 00:00 on day-of-month 1.
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    name: Update BSB Database & Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Update BSB Database & Version
        id: update-csvs
        working-directory: ./src/bsb/
        run: python ./updater/updater.py
      - id: get-date
        run: echo "date=$(date +'%B-%Y')" >> $GITHUB_OUTPUT
      - uses: peter-evans/create-pull-request@v5
        id: raise-pr
        with:
          branch: "bot/automate-sftp/${{ steps.get-date.outputs.date }}"
          base: automate-sftp-update
          title: "chore: update bsb directory with ${{ steps.get-date.outputs.date }} data"
          commit-message: "chore: update bsb directory with ${{ steps.get-date.outputs.date }} data"
          body: "Updated csv files using files: ${{ steps.update-csvs.outputs.bsb_prefix_file }}
                  and ${{ steps.update-csvs.outputs.bsb_directory_file }}.
                  
                  Auto-generated by create-pull-request
                  [https://github.com/peter-evans/create-pull-request]"
          committer: GitHub Actions <actions@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true